# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Deploy and manage services on Ink"
  homepage "https://ml.ink"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mldotink/cli/releases/download/v0.1.0/ink_0.1.0_darwin_amd64.tar.gz"
      sha256 "68a5d167b5d8f2c9c1e4168b1749c3d309811da9da01a6b9b7d78780cb568e25"

      define_method(:install) do
        bin.install "ink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mldotink/cli/releases/download/v0.1.0/ink_0.1.0_darwin_arm64.tar.gz"
      sha256 "9f18eb1912f8ea148ce838bb0b61c167a3babe714ba0e7ce38343ffa01a458b8"

      define_method(:install) do
        bin.install "ink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mldotink/cli/releases/download/v0.1.0/ink_0.1.0_linux_amd64.tar.gz"
      sha256 "caaca65da6a50902a78851b55e0813864016d66fa26d91a654c2b5e4db3074eb"
      define_method(:install) do
        bin.install "ink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mldotink/cli/releases/download/v0.1.0/ink_0.1.0_linux_arm64.tar.gz"
      sha256 "c3dfcaddf2365f00f7375015678e6bb1e7d4de9b2a19c2fe02908b3f622dd44c"
      define_method(:install) do
        bin.install "ink"
      end
    end
  end

  test do
    system "#{bin}/ink", "--version"
  end
end
