# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ink < Formula
  desc "Deploy and manage services on Ink"
  homepage "https://ml.ink"
  version "0.1.48"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mldotink/cli/releases/download/v0.1.48/ink_0.1.48_darwin_amd64.tar.gz"
      sha256 "7a082a42ce75d879a5d6f638b73c89642f498cf7994070b8873443fd4e560ee6"

      define_method(:install) do
        bin.install "ink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mldotink/cli/releases/download/v0.1.48/ink_0.1.48_darwin_arm64.tar.gz"
      sha256 "4a30271792b5cecd7259180c9f1bff357846c857d5cb489457d57b3170435754"

      define_method(:install) do
        bin.install "ink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mldotink/cli/releases/download/v0.1.48/ink_0.1.48_linux_amd64.tar.gz"
      sha256 "0dd1f9ea0174f7917ca5bc58a93971d62979fc76e44cd0272447715e534b61c7"
      define_method(:install) do
        bin.install "ink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mldotink/cli/releases/download/v0.1.48/ink_0.1.48_linux_arm64.tar.gz"
      sha256 "bec48f414506734e007d98acfa71015a9615dab713eb0db58c1f3d3edda64197"
      define_method(:install) do
        bin.install "ink"
      end
    end
  end

  test do
    system "#{bin}/ink", "--version"
  end
end
